2018-07-19 14:23:09,984 ERROR 27825 nodejs.unhandledExceptionError: write EIO
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
code: 'EIO'
errno: 'EIO'
syscall: 'write'
name: 'unhandledExceptionError'
pid: 27825
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:23:09,985 ERROR 27825 nodejs.unhandledExceptionError: write EIO
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
code: 'EIO'
errno: 'EIO'
syscall: 'write'
name: 'unhandledExceptionError'
pid: 27825
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:28:19,660 ERROR 32045 nodejs.ClusterClientNoResponseError: client no response in 77878ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 32045
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:30:16,401 ERROR 32046 [-/undefined/-/189599ms GET /chart/getOrderDetailList] nodejs.ResponseError: socket hang up (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":4,"createSocketErrorCount":0,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":3,"requestCount":6,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
headers: {}
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ECONNRESET'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 2, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
headerSent: true
pid: 32046
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:31:19,672 ERROR 32045 nodejs.ClusterClientNoResponseError: client no response in 63267ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 32045
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:31:48,517 ERROR 32046 [-/::1/-/76958ms GET /chart/getOrderDetailList] nodejs.ResponseError: write EPIPE (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":6,"createSocketErrorCount":0,"closeSocketCount":5,"errorSocketCount":0,"timeoutSocketCount":4,"requestCount":9,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
code: 'EPIPE'
errno: 'EPIPE'
syscall: 'write'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 1, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
pid: 32046
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:33:19,688 ERROR 32045 nodejs.ClusterClientNoResponseError: client no response in 70488ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 32045
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:54:50,405 ERROR 33679 [-/::1/-/85764ms GET /chart/getOrderDetailList] nodejs.ResponseError: write EPIPE (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
code: 'EPIPE'
errno: 'EPIPE'
syscall: 'write'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 3, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
pid: 33679
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 14:56:10,448 ERROR 33679 [-/::1/-/35847ms GET /chart/getOrderDetailList] nodejs.ResponseError: socket hang up (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":3,"createSocketErrorCount":0,"closeSocketCount":2,"errorSocketCount":0,"timeoutSocketCount":1,"requestCount":4,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
headers: {}
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ECONNRESET'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 2, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
pid: 33679
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 15:04:53,189 ERROR 33678 nodejs.ClusterClientNoResponseError: client no response in 79199ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 33678
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 15:10:53,233 ERROR 33678 nodejs.ClusterClientNoResponseError: client no response in 63584ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 33678
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:08:25,240 ERROR 35242 [-/::1/-/42837ms GET /chart/getOrderDetailList] nodejs.ResponseError: write EPIPE (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":2,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
code: 'EPIPE'
errno: 'EPIPE'
syscall: 'write'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 1, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
pid: 35242
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:09:33,737 ERROR 33678 nodejs.ClusterClientNoResponseError: client no response in 67731ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 33678
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:10:35,683 ERROR 35257 [-/::1/-/125082ms GET /chart/getOrderDetailList] nodejs.AssertionError [ERR_ASSERTION]: status code must be a number
    at Object.set status [as status] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa/lib/response.js:85:5)
    at Object.status (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/delegates/index.js:92:31)
    at ChartController.getOrderDetailList (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:47:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
generatedMessage: false
name: 'AssertionError [ERR_ASSERTION]'
code: 'ERR_ASSERTION'
actual: false
expected: true
operator: '=='
pid: 35257
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:10:36,955 ERROR 35290 [-/::1/-/407ms GET /chart/getOrderDetailList] nodejs.TypeError: Assignment to constant variable.
    at ChartController.getOrderDetailList (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:43:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 35290
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:11:01,133 ERROR 35301 [-/::1/-/4536ms GET /chart/getOrderDetailList] nodejs.TypeError: Assignment to constant variable.
    at ChartController.getOrderDetailList (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:43:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 35301
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:12:33,765 ERROR 33678 nodejs.ClusterClientNoResponseError: client no response in 77590ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 33678
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:17:28,630 ERROR 35314 [-/::1/-/367961ms GET /chart/getOrderDetailList] nodejs.AssertionError [ERR_ASSERTION]: status code must be a number
    at Object.set status [as status] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa/lib/response.js:85:5)
    at Object.status (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/delegates/index.js:92:31)
    at ChartController.getOrderDetailList (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:47:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
generatedMessage: false
name: 'AssertionError [ERR_ASSERTION]'
code: 'ERR_ASSERTION'
actual: false
expected: true
operator: '=='
pid: 35314
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:17:49,698 ERROR 35314 [-/::1/-/9187ms GET /chart/getOrderDetailList] nodejs.AssertionError [ERR_ASSERTION]: status code must be a number
    at Object.set status [as status] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa/lib/response.js:85:5)
    at Object.status (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/delegates/index.js:92:31)
    at ChartController.getOrderDetailList (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:47:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
generatedMessage: false
name: 'AssertionError [ERR_ASSERTION]'
code: 'ERR_ASSERTION'
actual: false
expected: true
operator: '=='
pid: 35314
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:39:00,712 ERROR 35740 [-/::1/-/8ms GET /chart/getOrderDetailList] nodejs.SyntaxError: Identifier 'orderResult' has already been declared
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:351:31)

pid: 35740
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:44:34,196 ERROR 35739 nodejs.ClusterClientNoResponseError: client no response in 72975ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 35739
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:47:54,225 ERROR 35739 nodejs.ClusterClientNoResponseError: client no response in 60850ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 35739
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:49:58,417 ERROR 35959 [-/::1/-/45306ms GET /chart/getOrderDetailList] nodejs.ResponseError: socket hang up (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
headers: {}
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ECONNRESET'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 2, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
pid: 35959
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 16:54:07,659 ERROR 36109 [-/::1/-/23818ms GET /chart/getOrderDetailList] nodejs.ResponseError: socket hang up (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
headers: {}
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketOnEnd (_http_client.js:423:23)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
code: 'ECONNRESET'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 3, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
pid: 36109
hostname: qitmac000404deMacBook-Pro.local

2018-07-19 17:15:33,816 ERROR 36652 [-/::1/-/3854ms GET /chart/getDishRank] nodejs.ReferenceError: Invalid left-hand side in assignment
    at result.map (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:115:17)
    at Array.map (<anonymous>)
    at ChartController.getDishRank (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:107:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 36652
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:10:05,517 ERROR 42553 nodejs.ClusterClientNoResponseError: client no response in 60606ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 42553
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:12:13,819 ERROR 42627 [-/undefined/-/185517ms GET /chart/getOrderDetailList] nodejs.ResponseError: write EPIPE (req "error"), POST http://open.2dfire.com/router -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{},"sockets":{"open.2dfire.com:80:":1},"requests":{}})
headers: {}
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14)
code: 'EPIPE'
errno: 'EPIPE'
syscall: 'write'
name: 'ResponseError'
data: undefined
path: '/router'
status: -1
headers: {}
res: { status: -1, statusCode: -1, headers: {}, size: 0, aborted: false, rt: 3, keepAliveSocket: true, data: undefined, requestUrls: [ 'http://open.2dfire.com/router' ], timing: null, remoteAddress: '120.55.199.20', remotePort: 80 }
headerSent: true
pid: 42627
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:12:27,215 ERROR 42704 [-/::1/-/11ms GET /chart/getOrderDetailList] nodejs.SyntaxError: Identifier 'orderIdList' has already been declared
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:351:31)

pid: 42704
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:12:27,821 ERROR 42704 [-/::1/-/3ms GET /chart/getOrderDetailList] nodejs.SyntaxError: Identifier 'orderIdList' has already been declared
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:351:31)

pid: 42704
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:12:30,252 ERROR 42704 [-/::1/-/3ms GET /chart/getOrderDetailList] nodejs.SyntaxError: Identifier 'orderIdList' has already been declared
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at Object.classControllerMiddleware (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/loader/mixin/controller.js:84:20)
    at Object.callFn (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/index.js:36:21)
    at wrappedController (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/egg-core/lib/utils/router.js:322:18)
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/koa-router/lib/router.js:351:31)

pid: 42704
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:12:46,515 ERROR 42729 [-/::1/-/620ms GET /chart/getOrderDetailList] nodejs.ReferenceError: c is not defined
    at ChartController.getOrderDetailList (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:32:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 42729
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:14:05,546 ERROR 42553 nodejs.ClusterClientNoResponseError: client no response in 67814ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 42553
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:16:03,044 ERROR 42739 [-/::1/-/181832ms GET /chart/getOrderDetailList] nodejs.TypeError: Cannot read property 'dishList' of undefined
    at result.map (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:60:35)
    at Array.map (<anonymous>)
    at ChartController.getOrderDetailList (/Users/qitmac000404/Documents/personalJobs/dishBooking/app/controller/chart.js:59:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

pid: 42739
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 11:17:25,573 ERROR 42553 nodejs.ClusterClientNoResponseError: client no response in 66304ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/qitmac000404/Documents/personalJobs/dishBooking/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
name: 'ClusterClientNoResponseError'
pid: 42553
hostname: qitmac000404deMacBook-Pro.local

2018-07-20 12:08:39,866 ERROR 43235 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2018-07-20 12:08:44,061 ERROR 43235 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
2018-07-20 12:10:05,191 ERROR 43303 A client (undefined:NaN) error [ECONNRESET] occurred: read ECONNRESET
